version: '3.7'
services:
  # jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.42.0
    ports:
      - "14268:14268"   # jaeger-collector HTTP server (tracer provider)
      - "16686:16686"   # HTTP server (browser UI)
