version: '3.7'
services:
  # rabbitmq
  rabbitmq:
    image: rabbitmq:3.11.8
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # HTTP-API
    volumes:
      - ./data/:/var/lib/rabbitmq/
      - ./log/:/var/log/rabbitmq
