version: '3.7'
services:
  # minio
  minio:
    image: minio/minio:RELEASE.2023-02-27T18-10-45Z
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web user interface
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ADDRESS: ":9000"
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    command: server /data
    networks:
      - apps
  # createbucket
  createbucket:
    image: minio/mc:RELEASE.2023-02-28T00-12-59Z
    deploy:
      replicas: 1
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rm -r --force myminio/default;
      /usr/bin/mc mb myminio/default;
      /usr/bin/mc policy download myminio/default;
      exit 0;
      "
    networks:
      - apps
  # createbackup
  createbackup:
    image: minio/mc:RELEASE.2023-02-28T00-12-59Z
    depends_on:
      - minio
    volumes:
      - ./backup:/backup
    entrypoint: >
      sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc cp --recursive myminio/default /backup;
      exit 0;
      "
    networks:
      - apps
networks:
  apps:
    driver: bridge
