version: '3.7'
services:
  # dgraph
  dgraph:
    image: dgraph/standalone:v21.03.1
    volumes:
      - ./data:/dgraph
    ports:
      - 6080:6080
      - 8080:8080
      - 8000:8000
      - 9080:9080
